### ISSUE TITLE
Using pycassa 1.2.1-3 with Cassandra 0.7.4

### ISSUE THREAD

**Issue by musabbir-khan** [pycassa/pycassa#86]
Trying to create a connection pool but it doesn't work.  It seems that this version of pycassa actually works with Cassandra 0.8.6 and above (that's what I have tested so far).  Is this true?

My code looks like this -- (pretty much taken from the example code) --

import pycassa

pool = pycassa.connect('mykeyspace', ['10.140.14.24:9160'])
cf = pycassa.ColumnFamily(pool, 'ACCOUNT');

The last line throws error.  And here is what the error looks like -- 

  File "C:\MyProgs\Python27\lib\site-packages\pycassa-1.2.1_3-py2.7.egg\pycassa\pool.py", line 356, in **init**
    self.fill()
  File "C:\MyProgs\Python27\lib\site-packages\pycassa-1.2.1_3-py2.7.egg\pycassa\pool.py", line 415, in fill
    conn = self._create_connection()
  File "C:\MyProgs\Python27\lib\site-packages\pycassa-1.2.1_3-py2.7.egg\pycassa\pool.py", line 403, in _create_connection
    (exc.__class__.__name, exc))
AttributeError: type object 'TTransportException' has no attribute '_ConnectionPool__name'

Any suggestion, please?  Thanks.
